sudo: require

matrix:
  include:
   - os: linux
     arch: arm64     
before_install:
  - sudo apt update
  - sudo apt install -y qemu kpartx
script:
  - sudo bash build_chroot.sh
cache:
  directories:
  - $HOME/travis_cache
